const DEFAULT_CHART_PADDING = 20;
const DEFAULT_CHART_MARGIN = 10;

const DEFAULT_CHART_WIDTH = 200;
const DEFAULT_CHART_HEIGHT = 180;

const DEFAULT_DASHBOARD_WIDTH_UNIT = 8;
const DEFAULT_DASHBOARD_HEIGHT_UNIT = 4;

const DEFAULT_DASHBOARD_GAP = 10;

export {
  DEFAULT_CHART_PADDING,
  DEFAULT_CHART_MARGIN,

  DEFAULT_CHART_WIDTH,
  DEFAULT_CHART_HEIGHT,

  DEFAULT_DASHBOARD_WIDTH_UNIT,
  DEFAULT_DASHBOARD_HEIGHT_UNIT,
  
  DEFAULT_DASHBOARD_GAP
}
